[
  {
    "center": [
      0.5,
      0.918592
    ],
    "kind": "ud",
    "match": "start",
    "module": "gf9598",
    "project": [
      "pd2453"
    ],
    "shooter": 12,
    "size": [
      0.16973125,
      0.0763796
    ]
  },
  {
    "center": [
      0.5,
      0.918592
    ],
    "kind": "ud",
    "match": "start",
    "module": "jv0307",
    "project": [
      "pd2453"
    ],
    "shooter": 12,
    "size": [
      0.16973125,
      0.0763796
    ]
  }
]